Website New Update
mgguild/msw-website pull request #201
Opened 2023-07-11 13:05 UTC by vkth

This resolves the following issues:

Issue #194 Removing Mint Section 7bf6b17bc7e5e035737e4c4a454190c62406a1da
![image](https://github.com/mgguild/msw-website/assets/42258463/32c222d5-6d07-4a4e-9a87-97b4a073023c)

Issue #195 Reduce Navbar's thickness 12300e7338fcfb9902456c842b08508cdbddd550
![image](https://github.com/mgguild/msw-website/assets/42258463/8b4f0f2f-8b98-4fcc-8c1c-04a8aeeca89f)

Issue #198 Remove this section and from navbar 1a467e8ca0b62adf03bbb0f887072f431bb577c7
Remove one of ones section and from the navbar.
![image](https://github.com/mgguild/msw-website/assets/42258463/6ebec127-45fe-4708-a6a9-87a000ffdb21)

Issue #200 Update FAQs 58838c34ab73c98ed25d8d6e7be099c488a3bd5f
![image](https://github.com/mgguild/msw-website/assets/42258463/1236f6dc-1ac5-436c-836e-9dfcba3a864c)

#199 Replace comics with 'Gallery' (Partial) 23b9a05a378e1f2555789222e21d9d0e93f0061b
![image](https://github.com/mgguild/msw-website/assets/42258463/7c3cce10-c2e0-49a9-a283-57cb28866c11)

2023-07-11 14:47 UTC, EAdornado requested changes
There is a line appearing on navbar. 
![image](https://github.com/mgguild/msw-website/assets/57949551/91474cf6-6624-4b3f-adc1-eaea2b85d080)

Thickness of the navbar changes when you are scrolling at the top part. 
![image](https://github.com/mgguild/msw-website/assets/57949551/4908f28e-35a1-4452-b487-e36eda4de454)

2023-07-12 01:34 UTC, swengr-janan commented
@vkth su sa Gallery section iyo na ito ang gamiton mo na image na tig send ko, bako arog kaan. Dapat kaan 1 whole new page.

2023-07-12 04:32 UTC, EAdornado commented
Make the gallery photo clickable for mobile. since its too small for mobile version

2023-07-12 05:40 UTC, EAdornado approved these changes

2023-07-12 05:40 UTC, merged